version: 2
updates:
- package-ecosystem: composer
  directory: "/app"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: development
  reviewers:
  - luciano-jr
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  - dependency-type: indirect
