name: PHP Unit

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: PHPUnit (php-actions)
        uses: php-actions/phpunit@v9
        working-directory: ./app
        with:
          configuration: phpunit.xml.dist
